2020-02-05 16:37:09,926 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:48]
2020-02-05 16:40:35,463 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:50]
2020-02-05 16:41:38,970 ERROR: Exception on /unfollow/Alexey [GET] [in c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "c:\users\a_smi\pycharmprojects\microblog\venv\app\routes.py", line 125, in unfollow
    if user is none:
NameError: name 'none' is not defined
2020-02-05 16:42:41,267 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:50]
2020-02-05 16:57:16,869 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:52]
2020-02-05 16:58:22,693 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:52]
2020-02-05 16:59:53,709 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:52]
2020-02-05 17:03:05,150 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:52]
2020-02-05 17:10:01,579 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:52]
2020-02-05 17:17:18,028 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:52]
2020-02-06 20:35:51,105 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-06 20:37:12,276 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-06 20:37:57,324 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-06 20:38:14,015 ERROR: Exception on /index [GET] [in c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2241, in preprocess_request
    rv = func()
  File "c:\users\a_smi\pycharmprojects\microblog\venv\app\routes.py", line 18, in before_request
    g.locale = str(get_locale())
NameError: name 'g' is not defined
2020-02-06 20:38:57,436 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-06 20:47:42,545 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-06 20:47:46,285 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:11:52,848 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:13:12,865 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:17:13,824 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:17:25,177 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:19:51,826 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:19:59,685 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:20:19,637 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:20:46,737 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:21:21,243 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:21:31,463 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:22:05,362 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:25:46,346 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:26:33,420 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:27:20,105 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:27:26,684 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:27:35,794 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:29:21,957 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:29:27,762 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:29:35,702 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:33:01,651 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:33:36,957 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:33:38,597 ERROR: Exception on /user/lexa [GET] [in c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2241, in preprocess_request
    rv = func()
  File "c:\users\a_smi\pycharmprojects\microblog\venv\app\routes.py", line 18, in before_request
    g.locale = str(get_locale())
  File "c:\users\a_smi\pycharmprojects\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py", line 59, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: name 'request' is not defined
2020-02-07 10:34:28,733 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:35:46,902 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 10:37:12,721 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
2020-02-07 11:21:13,754 INFO: Microblog startup [in C:\Users\a_smi\PycharmProjects\microblog\venv\app\__init__.py:55]
2020-02-07 12:01:42,037 INFO: Microblog startup [in c:\users\a_smi\pycharmprojects\microblog\venv\app\__init__.py:55]
